### ISSUE TITLE
__str__ method not used when coupled with wagtailmodelchooser

### ISSUE THREAD

**Issue by brianedelman** [wagtail/wagtail-react-streamfield#44]
I am using wagtailmodelchooser for a project and am using this package as well. Model chooser fields aren't showing up with a __str__ representation of the object. I removed the react stream fields and am able to see them with the default setup.
![Screen Shot 2019-08-08 at 12 56 18 PM](https://user-images.githubusercontent.com/14008969/62722520-97121880-b9dc-11e9-9952-3b1868ff4285.png)
This is how it looks without:
![Screen Shot 2019-08-08 at 1 05 15 PM](https://user-images.githubusercontent.com/14008969/62722788-32a38900-b9dd-11e9-86ec-0b7abb79f1cf.png)

I can investigate more deeply and potentially create a PR when I get some time.

**Comment by BertrandBordage** [comment]
This is the same issue as https://github.com/wagtail/wagtail-react-streamfield/issues/26.
It’s because the JavaScript widget does not correctly implements the `change` method, an issue I had to work around to make the official choosers work.
There’s nothing wagtail-react-streamfield can do about it.

I’m closing this issue in favor of #26.
