### ISSUE TITLE
it is destroying streamforms app 

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail-react-streamfield#57]
whenever I include "wagtail-react-streamfield" into "installed app", it making the streamfield unavailable, if the streamfields' blocks customized, otherwise no issues happens..!

check that please

**Comment by BertrandBordage** [comment]
I tried to use it and faced indeed a JS crash when trying to add a `WagtailFormBlock`.
It’s because wagtailstreamforms uses a hack to display some text in the StructBlock: it uses `InfoBlock`, a subclass of `CharBlock` that doesn’t render an HTML input. This is not in line with what React StreamField expects, because all `CharBlocks` must render an HTML input.

I tried modifying `WagtailFormBlock` so that it uses a `StaticBlock` instead, and it worked:
```python
form_reference = blocks.StaticBlock(
    admin_text=_("This form will be given a unique reference once saved"),
)
```
So wagtailstreamforms has to do something like that to support wagtail-react-streamfield. The good thing is that it’s backwards compatible with the existing StreamField.

Note that this will show a `Form reference` label above the block. To work around that, wagtailstreamforms can rewrite its `InfoBlock` this way:
```python
class InfoBlock(blocks.StaticBlock):
    @property
    def definition(self):
        definition = super().definition
        definition['label'] = None
        return definition

form_reference = blocks.StaticBlock(
    admin_text=_("This form will be given a unique reference once saved"),
)
```

It will look like this:
![image](https://user-images.githubusercontent.com/1119169/89413492-31f51e00-d729-11ea-97a7-4e587d2340da.png)
