### ISSUE TITLE
Recommended way to init JavaScript?

### ISSUE THREAD

**Issue by globophobe** [wagtail/wagtail-react-streamfield#58]
Wagtail docs suggest `js_initializer`, but that didn't seem to work.

This worked:

```
def render_form(self, *args, **kwargs):
    form = super().render_form(*args, **kwargs)
    return form + "<script>jsInitializer()</script>"
```

What is the recommended way?

**Comment by BertrandBordage** [comment]
That is right, the Python method `js_initializer` is removed with React StreamField.
Could you point to me the part of the Wagtail documentation mentioning `js_initializer`? I cannot find it.
`js_initializer` is just used to initialize the StreamField structure itself, not its block widgets.

So I’m also wondering: what is your use case? What are you trying to initialize, the JS from a block widget, or the JS from the StreamField itself?

**Comment by globophobe** [comment]
Oops, not the docs. I think it was https://github.com/wagtail/wagtail/wiki/StreamField-blocks-API#js_initializerself

I would like to init JS of a block widget.

**Comment by BertrandBordage** [comment]
It works like the existing StreamField. Include an inline `<script>` tag at the end of your widget’s template.
Look at Wagtail for examples. For the date widget, it defines [a custom widget](https://github.com/wagtail/wagtail/blob/33e4c0ec7b889131740ee66a954f4ca2293fc2dd/wagtail/admin/widgets/datetime.py) that renders [this template containing a script](https://github.com/wagtail/wagtail/blob/8fc722a6f3e4d25c09f99937d387ba521aa713dc/wagtail/admin/templates/wagtailadmin/widgets/date_input.html). It also references [this JavaScript file](https://github.com/wagtail/wagtail/blob/33e4c0ec7b889131740ee66a954f4ca2293fc2dd/wagtail/admin/static_src/wagtailadmin/js/date-time-chooser.js) that contains the front-end logic. It’s better to put as much logic in a JS file like this, so that each new block just contains a script like `<script>initWidget("{{ widget.attrs.id|escapejs }}")</script>`, reducing the browser loading time.
